[package]
name = "c_nn"
version = "0.1.0"
edition = "2024"

[dependencies]
lib-genetic-algorithm = { path = "libs/genetic-algorithm" }
lib-neural-network = { path = "libs/neural-network" }
rand = "0.9.2"

[workspace]
resolver = "2"
members = [
    "libs/*",
]
