[package]
name = "evolution-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
approx = "0.5.1"
rand = "0.9.2"
lib-genetic-algorithm = { path = "libs/genetic-algorithm" }
lib-neural-network = { path = "libs/neural-network" }

[workspace]
resolver = "2"
members = [
    "libs/*",
]
